name: medio_ambiente_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter: { sdk: flutter }
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  # Localización
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  # Mapa (OSM)
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  # PDF viewer
  pdfx: ^2.6.0

  # (Opcional) Carousel para Inicio
  carousel_slider: ^5.0.0
  flutter_map_marker_cluster: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/